services:
  voice-identity:
    restart: unless-stopped
    build: .
    volumes:
      - voice_identity_data:/data
    depends_on:
      - qdrant

  qdrant:
    restart: unless-stopped
    image: qdrant/qdrant:latest
    environment:
      - QDRANT__STORAGE__DATA_PATH=/data/qdrant
    volumes:
      - qdrant_data:/data

volumes:
  voice_identity_data:
  qdrant_data:
