version: '3.8'

services:

  voice-identity:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    volumes:
      - data:/data
    depends_on:
      - qdrant

  qdrant:
    restart: unless-stopped
    image: qdrant/qdrant:latest
    environment:
      - QDRANT__STORAGE__DATA_PATH=/data/qdrant
    volumes:
      - data:/data
    ports:
      - "6333:6333"
